name: Generate Asset Links

on:
  push:
    branches:
      - main

jobs:
  generate-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt || true

    - name: Run script to generate index.html
      run: python generate_links.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add index.html
        git commit -m "Update index.html with asset links" || echo "No changes to commit"
        git push
